### ISSUE TITLE
Suggestion to include badges/achievements

### ISSUE THREAD

**Issue by aneeqaabid** [Tarteel-io/tarteel-api#157]
Every time a user completes 100, 500, 1000, etc. ayahs, they should earn some sort of reward, like confetti exploding once they reach a milestone and a badge on their user profile.

Another suggestion is recommending users to recite certain ayahs that Tarteel does not have any or few recordings of. Perhaps an ayah map could be useful--showing users which ayahs have been recited more frequently and which have been recited less frequently.

**Comment by piraka9011** [comment]
Add this to a users model.

**Comment by piraka9011** [comment]
Implemented in API, time to update frontend.
