### ISSUE TITLE
Start Ayahs with demographic info

### ISSUE THREAD

**Issue by piraka9011** [Tarteel-io/tarteel-api#178]
I'm noticing that sometimes default values can be used in the demographics and it would be better to get that at the start instead of at the end of the recitations to make sure we have that info. 

@bahaa96 @tifa2UP thoughts?

**Comment by bahaa96** [comment]
Oh old one. I noticed that while I was working on our latest problem with the server and the cors and wanted to ask you what do you think the best way to do this ? Should we start asking for the demographics before any kinda recitation or we only need to send the ID related_demographics with the recording.

**Comment by tifa2UP** [comment]
We'll actually have a slightly newer UI that @moumen-soliman will be working on to push people to share their demographic info. The design is in sketch cloud. 

We don't have to worry about this for now, closing the issue but feel free to reopen
