### ISSUE TITLE
Evaluator not saving evaluations

### ISSUE THREAD

**Issue by abidlabs** [Tarteel-io/tarteel-api#187]
The evaluator throws a 500 internal server error whenever an evaluation is made, with the following error:

KeyError
'recording_id'
/app/restapi/views.py in post, line 446

See the screenshot below for more information:

![image](https://user-images.githubusercontent.com/1778297/52531935-dc75b780-2cd1-11e9-863e-fb8891f35303.png)

**Comment by piraka9011** [comment]
#193 Fixes this.
