### ISSUE TITLE
Session isn't stored or saved

### ISSUE THREAD

**Issue by mmayet** [Tarteel-io/tarteel-api#200]
![Screenshot_20190401-125548~2](https://user-images.githubusercontent.com/6694374/55355652-c5577880-547d-11e9-8bd5-8e4e53dd1601.png)

Both chrome on Windows and Android 9 don't seem to save my profile? I see the ayāt counter go up, but my profile is always empty.

https://www.tarteel.io/profile/%7B%60https://facebook.com/sharer/sharer.php?u=https://www.tarteel.io/profile/${sessionKey}`}

That's the link generated on the share.

I've had this issue for a while. Refreshing or deleting cookies doesn't help.

**Comment by mmayet** [comment]
The actual link of current page: https://www.tarteel.io/profile/undefined

The verses are incrementing so idk

**Comment by piraka9011** [comment]
Hmm interesting, will investigate.

**Comment by piraka9011** [comment]
@bahaa96 API is [sending](https://github.com/Tarteel-io/tarteel-api/blob/68ad058d53394f727b87adb5311e74bbfdcec7d7/restapi/views.py#L454) the session ID. Is this something with the frontend?

**Comment by piraka9011** [comment]
Fixed with recent fixes and refactoring
